default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: gdo_api_development
  cache:
    <<: *default
    database: gdo_api_development_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: gdo_api_development
    migrations_paths: db/queue_migrate

test:
  <<: *default
  database: gdo_api_test

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
  cache:
    <<: *primary_production
    url: <%= ENV["CACHE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    url: <%= ENV["QUEUE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
    migrations_paths: db/queue_migrate